#!/usr/bin/with-contenv bash

#if [ -f /mount-config/win-credentials.ini ]; then
  if [ ! -d /mnt/tv2 ]; then
    echo 'Create directory /mnt/remote-music'
    mkdir /mnt/remote-music
  fi

  echo 'mounting /mnt/remote-music'
  mount -v -t nfs4 '//192.168.68.163/mnt/user/media' /mnt/remote-music
#fi
